### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by trimad** [antiHUMANDesigns/dall-e-mega#1]
When I follow your instructions and run "python app.py 8080" for the backend I get the following error:

`
C:\Users\Administrator\Documents\GitHub\dall-e-mega\backend>python app.py 8080
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\dall-e-mega\backend\app.py", line 13, in <module>
    from dalle_mini import DalleBart, DalleBartProcessor
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\dalle_mini\__init__.py", line 3, in <module>
    from .model import DalleBart, DalleBartProcessor
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\dalle_mini\model\__init__.py", line 2, in <module>
    from .modeling import DalleBart
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\dalle_mini\model\modeling.py", line 28, in <module>
    from flax.linen import partitioning as nn_partitioning
ImportError: cannot import name 'partitioning' from 'flax.linen' (C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\flax\linen\__init__.py)`

**Comment by trimad** [comment]
Disregard, I was about to get past this by running these commands in the backend directory: https://flax.readthedocs.io/en/latest/installation.html
